clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:

  frontend:
    image: node:8.1.2
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install
      - yarn run production

  backend:
    image: laradock/workspace:1.8-71
    commands:
      - php -v
      - composer -V
      - composer install --prefer-dist
      - ./vendor/bin/phpunit
